name: Autograding - Linux User Assignment

'on':
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          echo "Checking repository..."
          ls -la
          echo "Checking tests directory..."
          ls -la tests
          echo "Checking starter directory..."
          ls -la starter

      - name: Run autograding tests
        run: sudo bash tests/test_solution.sh
